[GoldenDict]
Executable=goldendict
; GoldenDict → Edit → Preferences → Hotkeys → "... translate a word from clipboard" toggle: on=on, off=off(default)
ClipboardHotkeyEnabled=off

; Max 10 groups (Group_1 to Group_10)
[Groups]
; Dictionaries group in GoldenDict
Group_1=default
Group_2=translate
Group_3=grammar

[Hotkeys]
Group_1=!+z
Group_2=!+x
Group_3=!xx

[Messages]
NoSelectionMsg=No text copied. Please select the word to query first.

; Default is %EDITOR%, fallback notepad
[AutoHotkey]
ScriptEditor=
