[GoldenDict]
Executable=goldendict
DefaultWindowMode=popup

[Groups]
; Dictionaries group in GoldenDict
Group_1=default
Group_2=standby
Group_3=translate
Group_4=grammar

[WindowModes]
; In the main window
Group_1=main
Group_2=main
; In the pop-up window
Group_3=popup
Group_4=popup

[Hotkeys]
TriggerKey=!
z=default
z_Double=translate
x=standby
x_Double=grammar

[Messages]
NoSelectionMsg=No text copied. Please select the word to query first.