[GoldenDict]
Executable=goldendict

[Groups]
PrimaryGroup=default
SecondaryGroup=translate

[Hotkeys]
; Alt+z
PrimaryHotkey=!z
; Alt+Shift+z
SecondaryHotkey=!+z

[Messages]
NoSelectionMsg=No text copied. Please select the word to query first.